---
- hosts: all
  tasks:
    - name: Propose pull request to GitHub
      block:
        - name: Create github credentials
          copy:
            content: "{{ github_proposal_bot.token }}"
            dest: ~/.netrc
            mode: 0600

        - name: Install git-pull-request
          shell: pip3 install "git-pull-request<3.0.0" --user

        - name: Create pull request
          args:
            chdir: "{{ proposal_project_src }}"
            executable: /bin/bash
          environment:
            GIT_EDITOR: cat
          shell: git pull-request

      always:
        - name: Shred github credentials
          shell: shred ~/.netrc

    when: zuul_success | bool
