---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Run ara-report role
      include_role:
        name: ara-report

    - name: Run htmlify-logs role
      include_role:
        name: htmlify-logs

    - name: Run Zuul manifest role
      include_role:
        name: generate-zuul-manifest

    - name: Run upload-logs-swift role
      no_log: true
      include_role:
        name: upload-logs-swift
      vars:
        zuul_log_partition: true
        zuul_log_container: ansible
        zuul_log_cloud_config: "{{ item }}"
      with_random_choice:
        - "{{ rackspace_dfw_clouds_yaml }}"
